Edit URL (API Added)
webdev-20/TLL-hacktoberfest-2022 pull request #39
Opened 2022-10-02 14:27 UTC by harshilsharmaa

## Summary
API to Edit already existed URL 

![Capture](https://user-images.githubusercontent.com/71216106/193459297-825a2993-3f93-48ea-a403-e7dc57432f1e.PNG)

2022-10-03 22:34 UTC, cherylli requested changes
is the code tested locally? Also, I would like to use the short code instead of the id. otherwise looks good. Thanks for updating the api docs as well

2022-10-03 22:34 UTC, cherylli commented on server/src/controllers/links.controller.js
> +        const link = await Link.findById(req.params.urlID)
we don't use the id. the short code would be enough as it's unique

2022-10-04 01:21 UTC, harshilsharmaa commented
API updated.
Now we have to just pass the short code in params.

API is tested and working fine.

2022-10-04 03:10 UTC, cherylli commented
a suggestion for next time is not to use main to merge into main, it was a bit confusing when resolving conflicts...

2022-10-04 03:22 UTC, merged